version: '3'

services:
  mysql-koole:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=koole-db
    volumes:
      - db-data:/var/lib/mysql:cached

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql-koole
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "9000:80"



volumes:
  db-data:
